### ISSUE TITLE
Not a good starter project

### ISSUE THREAD

**Issue by Orasund** [lamdera/elm-spa-lamdera#2]
So I forked this project as used it as a starting point.

After adding a Button that sends a message to the backend, I encountered a dependency loop:

Home_ -> Types -> Gen.Pages -> .. -> Home_

The way this can be broken is using the bridge technique as seen in the lamdera realworld project: moving ToBackend into a separate module. Might be nice if this small change could be added.

**Comment by supermario** [comment]
Hey @Orasund – thanks for the feedback!

I've now included the bridge setup by default. 👍
